services:
  - type: web
    name: casevault-demo
    env: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
