import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, ArrowRight, CheckCircle2, Download, Fingerprint, Search, ShieldAlert, ShieldCheck } from "lucide-react";
import { get } from "../api";
import { useWorkspace } from "../context";
import type { AuditEvent } from "../types";
import { Empty, fmtDate, Loading, PageHeading, label } from "../ui";

type Integrity = { valid: boolean; checked: number; head?: string; broken_at?: number };

export default function ActivityPage() {
  const { user, refreshKey, notify } = useWorkspace(); const [events, setEvents] = useState<AuditEvent[] | null>(null); const [search, setSearch] = useState(""); const [integrity, setIntegrity] = useState<Integrity | null>(null); const [checking, setChecking] = useState(false);
  useEffect(() => { get<AuditEvent[]>("/audit?limit=300").then(setEvents).catch(error => notify(error.message, true)); }, [refreshKey]);
  async function check() { setChecking(true); try { const result = await get<Integrity>("/audit/verify"); setIntegrity(result); notify(result.valid ? `Audit chain verified across ${result.checked} events.` : `Audit chain broken at event ${result.broken_at}.`, !result.valid); } catch (error) { notify(error instanceof Error ? error.message : "Verification failed.", true); } finally { setChecking(false); } }
  function exportCsv() { if (!events) return; const rows = [["Event ID", "Timestamp", "Actor", "Action", "Case ID", "Target ID", "Event hash"], ...events.map(event => [event.id, event.created_at, event.actor_name, event.action, event.case_id ?? "", event.target_id ?? "", event.event_hash])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "casevault-audit.csv"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 30000); }
  const filtered = events?.filter(event => `${event.action} ${event.actor_name} ${event.case_id ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeading eyebrow="ACCOUNTABILITY" title="Audit trail" description="A trace of case activity, evidence access, and review decisions." action={<div className="heading-action">{(user.role === "admin" || user.role === "auditor") && <button className="button button-secondary" disabled={checking} onClick={check}><ShieldCheck size={17} /> {checking ? "Checking…" : "Verify chain"}</button>}<button className="button button-secondary" onClick={exportCsv} disabled={!events?.length}><Download size={17} /> Export CSV</button></div>} />{integrity && <div className={`integrity-banner ${integrity.valid ? "integrity-good" : "integrity-bad"}`}>{integrity.valid ? <CheckCircle2 size={21} /> : <ShieldAlert size={21} />}<div><strong>{integrity.valid ? "Audit chain verified" : "Integrity check failed"}</strong><span>{integrity.valid ? `${integrity.checked} linked events checked · Head ${integrity.head?.slice(0, 24)}…` : `Broken at event ${integrity.broken_at}. Investigate the audit store.`}</span></div></div>}<div className="panel"><div className="list-toolbar"><div className="search-field"><Search size={18} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search action, actor, or case ID" aria-label="Search audit events" /></div><span className="list-count">{filtered?.length ?? 0} events</span></div>{!events ? <Loading /> : filtered?.length ? <div className="audit-list">{filtered.map(event => <div className="audit-row" key={event.id}><span className="audit-icon"><Activity size={18} /></span><div className="audit-info"><strong>{label(event.action.replaceAll(".", " "))}</strong><span>{event.actor_name} · {fmtDate(event.created_at, { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}</span><code><Fingerprint size={12} /> {event.event_hash.slice(0, 32)}…</code></div>{event.case_id && <Link to={`/cases/${event.case_id}`} className="button button-secondary button-small">View case <ArrowRight size={14} /></Link>}</div>)}</div> : <Empty icon="search" title="No audit events found" description="Try a different search, or work in a case file to generate events." />}</div><p className="page-note">The chain is keyed to this installation. Independent proof requires an external trusted anchor and a managed key service.</p></>;
}
