import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { Activity, ArrowLeft, ArrowRight, CalendarDays, FileText, FolderClosed, LockKeyhole, Plus, ShieldCheck, UploadCloud, UsersRound } from "lucide-react";
import { get, patch, post, remove, upload } from "../api";
import { useWorkspace } from "../context";
import type { AuditEvent, CaseFile, Document, User } from "../types";
import { Badge, Empty, fmtDate, fmtSize, Loading, Modal, PageHeading, initials, label } from "../ui";
import DocumentPanel from "../DocumentPanel";

type Tab = "overview" | "documents" | "activity" | "access";
const KINDS = ["fir", "police_report", "witness_statement", "charge_sheet", "court_filing", "evidence", "forensic_report", "legal_notice", "judgment", "other"];

function UploadModal({ caseId, onClose, onDone }: { caseId: string; onClose: () => void; onDone: () => void }) {
  const { notify } = useWorkspace(); const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [kind, setKind] = useState("other"); const [classification, setClassification] = useState("confidential"); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!file) return; setBusy(true); try { const form = new FormData(); form.set("file", file); form.set("title", title || file.name); form.set("kind", kind); form.set("classification", classification); await upload(`/cases/${caseId}/documents`, form); notify("Document encrypted and added to the case."); onDone(); onClose(); } catch (error) { notify(error instanceof Error ? error.message : "Upload failed.", true); } finally { setBusy(false); } }
  return <Modal title="Add case document" eyebrow="SECURE UPLOAD" onClose={onClose}><form className="form-stack" onSubmit={submit}><label className="drop-zone"><UploadCloud size={25} /><strong>{file ? file.name : "Choose a file to secure"}</strong><span>PDF, DOCX, TXT, PNG or JPEG · up to 25 MB</span><input type="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg" onChange={event => { const next = event.target.files?.[0] ?? null; setFile(next); if (next && !title) setTitle(next.name.replace(/\.[^.]+$/, "")); }} required /></label><label>Document title<input value={title} onChange={event => setTitle(event.target.value)} maxLength={240} required placeholder="e.g. Witness statement" /></label><div className="form-grid"><label>Document type<select value={kind} onChange={event => setKind(event.target.value)}>{KINDS.map(item => <option value={item} key={item}>{label(item)}</option>)}</select></label><label>Classification<select value={classification} onChange={event => setClassification(event.target.value)}><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select></label></div><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy || !file}>{busy ? "Encrypting…" : "Secure document"}<ArrowRight size={16} /></button></div></form></Modal>;
}

export default function CaseDetailPage() {
  const { caseId } = useParams(); const { user, refreshKey, refresh, notify } = useWorkspace();
  const [item, setItem] = useState<CaseFile | null>(null); const [tab, setTab] = useState<Tab>("overview"); const [uploadOpen, setUploadOpen] = useState(false); const [selectedDoc, setSelectedDoc] = useState<Document | null>(null); const [users, setUsers] = useState<User[]>([]); const [events, setEvents] = useState<AuditEvent[]>([]); const [note, setNote] = useState(""); const [reviewer, setReviewer] = useState(""); const [reviewNote, setReviewNote] = useState(""); const [memberId, setMemberId] = useState(""); const [memberAccess, setMemberAccess] = useState("viewer"); const [busy, setBusy] = useState(false);
  const canManage = item && item.status !== "archived" && (user.role === "admin" || item.lead_user_id === user.id);
  function reload() { refresh(); }
  useEffect(() => { if (!caseId) return; get<CaseFile>(`/cases/${caseId}`).then(setItem).catch(error => notify(error.message, true)); }, [caseId, refreshKey]);
  useEffect(() => { if (tab === "access" || tab === "overview") get<User[]>("/users").then(setUsers).catch(() => undefined); if (tab === "activity" && caseId) get<AuditEvent[]>(`/audit?case_id=${caseId}`).then(setEvents).catch(error => notify(error.message, true)); }, [tab, caseId, refreshKey]);
  async function changeCase(payload: Record<string, unknown>, success: string) { if (!caseId) return; setBusy(true); try { const updated = await patch<CaseFile>(`/cases/${caseId}`, payload); setItem(updated); notify(success); refresh(); } catch (error) { notify(error instanceof Error ? error.message : "Update failed.", true); } finally { setBusy(false); } }
  async function addNote(event: FormEvent) { event.preventDefault(); if (!caseId) return; setBusy(true); try { await post(`/cases/${caseId}/notes`, { body: note }); setNote(""); notify("Note added to case file."); reload(); } catch (error) { notify(error instanceof Error ? error.message : "Could not add note.", true); } finally { setBusy(false); } }
  async function requestReview(event: FormEvent) { event.preventDefault(); if (!caseId) return; setBusy(true); try { await post(`/cases/${caseId}/reviews`, { assigned_to: reviewer, note: reviewNote }); setReviewer(""); setReviewNote(""); notify("Review assigned."); reload(); } catch (error) { notify(error instanceof Error ? error.message : "Could not request review.", true); } finally { setBusy(false); } }
  async function decide(reviewId: string, decision: string) { const note = window.prompt("Add a reason for this decision:"); if (!note?.trim()) return; setBusy(true); try { await patch(`/reviews/${reviewId}`, { status: decision, note }); notify("Review decision recorded."); reload(); } catch (error) { notify(error instanceof Error ? error.message : "Could not record decision.", true); } finally { setBusy(false); } }
  async function addMember(event: FormEvent) { event.preventDefault(); if (!caseId) return; setBusy(true); try { await post(`/cases/${caseId}/members`, { user_id: memberId, access: memberAccess }); setMemberId(""); notify("Case access updated."); reload(); } catch (error) { notify(error instanceof Error ? error.message : "Could not update access.", true); } finally { setBusy(false); } }
  async function removeMember(id: string) { if (!caseId || !window.confirm("Remove this person's case access?")) return; setBusy(true); try { await remove(`/cases/${caseId}/members/${id}`); notify("Case access removed."); reload(); } catch (error) { notify(error instanceof Error ? error.message : "Could not remove access.", true); } finally { setBusy(false); } }
  if (!item) return <Loading label="Loading case file…" />;
  return <><Link to="/cases" className="back-link"><ArrowLeft size={17} /> All case files</Link><PageHeading eyebrow={item.reference} title={item.title} description={item.description || "No description added."} action={<div className="heading-action"><Badge value={item.status} />{item.can_edit && <button className="button button-primary" onClick={() => { setTab("documents"); setUploadOpen(true); }}><UploadCloud size={17} /> Add document</button>}</div>} /><div className="case-meta-strip"><span><FolderClosed size={16} /> {label(item.category)}</span><span><ShieldCheck size={16} /> {label(item.classification)}</span><span><FileText size={16} /> {item.document_count} documents</span><span><CalendarDays size={16} /> Opened {fmtDate(item.created_at)}</span>{item.legal_hold && <span className="hold-label"><LockKeyhole size={16} /> Legal hold</span>}</div><div className="tabs" role="tablist">{([{ key: "overview", icon: FolderClosed, text: "Overview" }, { key: "documents", icon: FileText, text: "Documents" }, { key: "activity", icon: Activity, text: "Activity" }, { key: "access", icon: UsersRound, text: "Access" }] as const).map(entry => <button key={entry.key} className={`tab ${tab === entry.key ? "tab-active" : ""}`} onClick={() => setTab(entry.key)} role="tab" aria-selected={tab === entry.key}><entry.icon size={17} /> {entry.text}</button>)}</div>
    {tab === "overview" && <div className="detail-grid"><div className="detail-main"><section className="panel panel-pad"><div className="panel-head"><div><div className="eyebrow">CASE DETAILS</div><h2>File overview</h2></div></div><div className="detail-fields"><div><span>Reference number</span><strong>{item.reference}</strong></div><div><span>Category</span><strong>{label(item.category)}</strong></div><div><span>Classification</span><Badge value={item.classification} /></div><div><span>Retention until</span><strong>{item.retention_until ? fmtDate(item.retention_until) : "No date set"}</strong></div><div><span>Case lead</span><strong>{users.find(person => person.id === item.lead_user_id)?.name ?? "—"}</strong></div><div><span>Legal hold</span><strong>{item.legal_hold ? "Enabled" : "Off"}</strong></div></div></section>
      <section className="panel panel-pad"><div className="panel-head"><div><div className="eyebrow">COLLABORATION</div><h2>Case notes</h2></div></div>{item.can_edit && <form onSubmit={addNote} className="note-form"><textarea value={note} onChange={event => setNote(event.target.value)} rows={3} maxLength={5000} required placeholder="Add context or an update for authorized colleagues…" /><button className="button button-secondary" disabled={busy || !note.trim()}><Plus size={16} /> Add note</button></form>}{item.notes?.length ? <div className="note-list">{item.notes.map(entry => <div className="note-item" key={entry.id}><span className="avatar avatar-small">{initials(entry.author.name)}</span><div><div><strong>{entry.author.name}</strong><small>{fmtDate(entry.created_at, { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</small></div><p>{entry.body}</p></div></div>)}</div> : <Empty title="No notes yet" description="Case updates and collaboration notes will appear here." />}</section></div>
    <div className="detail-side"><section className="panel panel-pad"><div className="eyebrow">CASE CONTROL</div><h2>Lifecycle</h2><p className="muted">Keep case status and preservation requirements current.</p><label className="compact-label">Status<select value={item.status} disabled={(!item.can_edit && !item.can_reopen) || busy} onChange={event => changeCase({ status: event.target.value }, "Case status updated.")}><option value="active">Active</option><option value="under_review">Under review</option><option value="closed">Closed</option><option value="archived">Archived</option></select></label><label className="compact-label">Retain until<input type="date" value={item.retention_until?.slice(0, 10) ?? ""} disabled={!item.can_edit || busy} onChange={event => changeCase({ retention_until: event.target.value ? new Date(`${event.target.value}T00:00:00Z`).toISOString() : null }, "Retention date updated.")} /></label><div className="toggle-row"><div><strong>Legal hold</strong><span>Preserve this case from archiving.</span></div><button className={`switch ${item.legal_hold ? "switch-on" : ""}`} role="switch" aria-checked={item.legal_hold} aria-label="Legal hold" disabled={!canManage || busy} onClick={() => changeCase({ legal_hold: !item.legal_hold }, item.legal_hold ? "Legal hold released." : "Legal hold enabled.")}><span /></button></div></section>
      <section className="panel panel-pad"><div className="eyebrow">HUMAN REVIEW</div><h2>Review queue</h2>{item.can_edit && <form className="form-stack review-form" onSubmit={requestReview}><label>Assign to<select value={reviewer} onChange={event => setReviewer(event.target.value)} required><option value="">Select reviewer</option>{users.filter(person => person.role === "admin" || item.members?.some(member => member.user.id === person.id)).map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Request note<input value={reviewNote} onChange={event => setReviewNote(event.target.value)} maxLength={2000} placeholder="What needs review?" /></label><button className="button button-secondary" disabled={busy || !reviewer}><Plus size={16} /> Request review</button></form>}{item.reviews?.length ? <div className="review-list">{item.reviews.map(review => <div className="review-item" key={review.id}><div><strong>{review.assigned_name}</strong><Badge value={review.status} /></div><small>Requested {fmtDate(review.created_at)}</small>{review.note && <p>{review.note}</p>}{review.status === "pending" && (review.assigned_to === user.id || user.role === "admin") && <div className="review-actions"><button className="button button-small button-primary" disabled={busy} onClick={() => decide(review.id, "approved")}>Approve</button><button className="button button-small button-secondary" disabled={busy} onClick={() => decide(review.id, "changes_requested")}>Request changes</button><button className="button button-small button-danger" disabled={busy} onClick={() => decide(review.id, "rejected")}>Reject</button></div>}</div>)}</div> : <p className="muted">No reviews requested yet.</p>}</section></div></div>}
    {tab === "documents" && <div className="panel"><div className="panel-head panel-head-pad"><div><div className="eyebrow">EVIDENCE LIBRARY</div><h2>Case documents</h2><p className="muted">Original versions stay available and can be verified at any time.</p></div>{item.can_edit && <button className="button button-secondary" onClick={() => setUploadOpen(true)}><UploadCloud size={17} /> Upload document</button>}</div>{item.documents?.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Document</th><th>Type</th><th>Classification</th><th>Versions</th><th>Latest file</th><th>Added</th><th /></tr></thead><tbody>{item.documents.map(doc => <tr key={doc.id}><td><button className="table-main table-button" onClick={() => setSelectedDoc(doc)}><span className="table-icon"><FileText size={18} /></span><span><strong>{doc.title}</strong><small>{doc.latest?.sha256.slice(0, 16)}…</small></span></button></td><td>{label(doc.kind)}</td><td><Badge value={doc.classification} /></td><td>{doc.versions.length}</td><td>{fmtSize(doc.latest?.byte_size)}</td><td>{fmtDate(doc.created_at)}</td><td><button className="table-arrow" onClick={() => setSelectedDoc(doc)} aria-label={`Open ${doc.title}`}><ArrowRight size={17} /></button></td></tr>)}</tbody></table></div> : <Empty title="No documents yet" description="Upload an FIR, witness statement, filing, or other record to this case." action={item.can_edit && <button className="button button-secondary" onClick={() => setUploadOpen(true)}><UploadCloud size={16} /> Upload document</button>} />}</div>}
    {tab === "activity" && <div className="panel panel-pad"><div className="panel-head"><div><div className="eyebrow">TRACEABILITY</div><h2>Case activity</h2></div><Link to="/activity" className="text-link">Full audit trail <ArrowRight size={16} /></Link></div>{events.length ? <div className="timeline">{events.map(event => <div className="timeline-event" key={event.id}><span className="timeline-icon"><Activity size={16} /></span><div><strong>{label(event.action.replaceAll(".", " "))}</strong><p>{event.actor_name} · {fmtDate(event.created_at, { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}</p><code>{event.event_hash.slice(0, 28)}…</code></div></div>)}</div> : <Empty title="No events recorded" description="Actions on this case will appear here." />}</div>}
    {tab === "access" && <div className="detail-grid"><section className="panel panel-pad"><div className="panel-head"><div><div className="eyebrow">CASE MEMBERSHIP</div><h2>People with access</h2></div></div><div className="member-list">{item.members?.map(member => <div className="member-row" key={member.user.id}><span className="avatar">{initials(member.user.name)}</span><div><strong>{member.user.name}</strong><small>{member.user.email}</small></div><Badge value={member.access} />{canManage && member.user.id !== item.lead_user_id && <button className="text-danger" disabled={busy} onClick={() => removeMember(member.user.id)}>Remove</button>}</div>)}</div></section><section className="panel panel-pad"><div className="eyebrow">PERMISSIONS</div><h2>Grant case access</h2><p className="muted">Only the case lead or an administrator can change membership.</p>{canManage ? <form className="form-stack" onSubmit={addMember}><label>Colleague<select value={memberId} onChange={event => setMemberId(event.target.value)} required><option value="">Choose a person</option>{users.filter(person => person.id !== item.lead_user_id && !item.members?.some(member => member.user.id === person.id)).map(person => <option key={person.id} value={person.id}>{person.name} · {person.role}</option>)}</select></label><label>Access level<select value={memberAccess} onChange={event => setMemberAccess(event.target.value)}><option value="viewer">Viewer</option><option value="editor">Editor</option></select></label><button className="button button-primary" disabled={busy || !memberId}><Plus size={16} /> Grant access</button></form> : <div className="permission-note"><LockKeyhole size={18} /> Ask the case lead to change access.</div>}</section></div>}
    {uploadOpen && caseId && <UploadModal caseId={caseId} onClose={() => setUploadOpen(false)} onDone={() => { setTab("documents"); reload(); }} />}{selectedDoc && <DocumentPanel document={selectedDoc} canEdit={item.can_edit} onUpdated={updated => { setSelectedDoc(updated); reload(); }} onClose={() => setSelectedDoc(null)} />}</>;
}
