import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Activity, ArrowRight, CheckCheck, FileText, FolderClosed, LockKeyhole, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { get, post } from "../api";
import { useWorkspace } from "../context";
import type { Summary } from "../types";
import { Badge, Empty, fmtDate, Loading, PageHeading } from "../ui";

const actionText: Record<string, string> = { "case.created": "created a case file", "case.updated": "updated a case file", "document.created": "added a document", "document.version_uploaded": "uploaded a document version", "document.downloaded": "downloaded evidence", "document.verified": "verified evidence integrity", "note.added": "added a case note", "review.requested": "requested a review", "review.decided": "completed a review", "access.granted": "granted case access", "access.revoked": "removed case access" };

export default function DashboardPage() {
  const { user, refreshKey, refresh, notify, openNewCase } = useWorkspace();
  const [data, setData] = useState<Summary | null>(null);
  const [seeding, setSeeding] = useState(false);
  useEffect(() => { get<Summary>("/summary").then(setData).catch(error => notify(error.message, true)); }, [refreshKey]);
  async function seed() { setSeeding(true); try { const result = await post<{ created: number; message: string }>("/demo/seed"); notify(result.message); refresh(); } catch (error) { notify(error instanceof Error ? error.message : "Could not add sample files.", true); } finally { setSeeding(false); } }
  const greeting = new Date().getHours() < 12 ? "Good morning" : new Date().getHours() < 17 ? "Good afternoon" : "Good evening";
  return <><PageHeading eyebrow="WORKSPACE OVERVIEW" title={`${greeting}, ${user.name.split(" ")[0]}`} description="A clear view of your cases, documents, and actions that need attention." action={user.role !== "auditor" && <button className="button button-primary" onClick={openNewCase}><Plus size={17} /> New case file</button>} />
    {!data ? <Loading /> : <><div className="metric-grid"><div className="metric-card"><div className="metric-icon metric-green"><FolderClosed size={20} /></div><div><span>Total cases</span><strong>{data.total_cases}</strong><small>Across your workspace</small></div></div><div className="metric-card"><div className="metric-icon metric-blue"><FileText size={20} /></div><div><span>Documents secured</span><strong>{data.documents}</strong><small>Versioned evidence files</small></div></div><div className="metric-card"><div className="metric-icon metric-amber"><CheckCheck size={20} /></div><div><span>My pending reviews</span><strong>{data.pending_reviews}</strong><small>Awaiting your decision</small></div></div><div className="metric-card"><div className="metric-icon metric-purple"><LockKeyhole size={20} /></div><div><span>Legal holds</span><strong>{data.legal_holds}</strong><small>Preservation enabled</small></div></div></div>
    {data.total_cases === 0 && <div className="welcome-panel"><div className="welcome-icon"><Sparkles size={22} /></div><div><div className="eyebrow">GET STARTED</div><h2>Your workspace is ready</h2><p>Create a case to upload evidence, or load fictional sample files to explore every workflow.</p></div><div className="welcome-actions">{user.role !== "auditor" && <button className="button button-primary" onClick={openNewCase}><Plus size={17} /> Create a case</button>}{user.role === "admin" && <button className="button button-secondary" onClick={seed} disabled={seeding}>{seeding ? "Adding samples…" : "Load sample cases"}</button>}</div></div>}
    <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><div className="eyebrow">CURRENT WORK</div><h2>Recent case files</h2></div><Link className="text-link" to="/cases">View all <ArrowRight size={16} /></Link></div>{data.recent_cases.length ? <div className="case-list">{data.recent_cases.map(item => <Link to={`/cases/${item.id}`} className="case-row" key={item.id}><div className="case-icon"><FolderClosed size={19} /></div><div className="case-main"><strong>{item.title}</strong><small>{item.reference} <span>·</span> {item.document_count} documents</small></div><Badge value={item.status} /><ArrowRight size={16} className="row-arrow" /></Link>)}</div> : <Empty title="No cases yet" description="Your recently accessed case files will appear here." />}</section>
    <section className="panel"><div className="panel-head"><div><div className="eyebrow">ACCOUNTABILITY</div><h2>Recent activity</h2></div><Link className="text-link" to="/activity">Audit trail <ArrowRight size={16} /></Link></div>{data.recent_activity.length ? <div className="activity-list">{data.recent_activity.map(event => <div className="activity-item" key={event.id}><span className="activity-marker"><Activity size={15} /></span><div><strong>{event.actor_name}</strong> {actionText[event.action] ?? event.action.replaceAll(".", " ")}<small>{fmtDate(event.created_at, { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</small></div></div>)}</div> : <Empty title="No activity yet" description="Recorded actions will appear as the team works." />}</section></div>
    <div className="assurance-strip"><span><ShieldCheck size={19} /> Evidence is encrypted before storage</span><span><Activity size={19} /> Every version carries a SHA-256 fingerprint</span><Link to="/activity">Inspect audit chain <ArrowRight size={15} /></Link></div></>}
  </>;
}
