import { useEffect, useState, type FormEvent } from "react";
import { Plus, UsersRound } from "lucide-react";
import { get, post } from "../api";
import { useWorkspace } from "../context";
import type { User } from "../types";
import { Badge, Empty, Loading, Modal, PageHeading, initials } from "../ui";

export default function TeamPage() {
  const { user, refreshKey, refresh, notify } = useWorkspace(); const [users, setUsers] = useState<User[] | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState("investigator"); const [busy, setBusy] = useState(false);
  useEffect(() => { get<User[]>("/users").then(setUsers).catch(error => notify(error.message, true)); }, [refreshKey]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await post("/users", { name, email, password, role }); notify("Team member created. Grant access within a case file."); setOpen(false); setName(""); setEmail(""); setPassword(""); refresh(); } catch (error) { notify(error instanceof Error ? error.message : "Could not add team member.", true); } finally { setBusy(false); } }
  return <><PageHeading eyebrow="ACCESS MANAGEMENT" title="People & access" description="Create organization accounts and grant case specific permissions from each case file." action={user.role === "admin" && <button className="button button-primary" onClick={() => setOpen(true)}><Plus size={17} /> Add person</button>} /><div className="panel"><div className="panel-head panel-head-pad"><div><div className="eyebrow">ORGANIZATION</div><h2>Team directory</h2></div><span className="list-count">{users?.length ?? 0} people</span></div>{!users ? <Loading /> : users.length ? <div className="member-list team-list">{users.map(person => <div className="member-row" key={person.id}><span className="avatar">{initials(person.name)}</span><div><strong>{person.name}</strong><small>{person.email}</small></div><Badge value={person.role} tone={person.role === "admin" ? "blue" : person.role === "auditor" ? "amber" : "neutral"} /><span className="team-status"><span className="online-dot" /> Active</span></div>)}</div> : <Empty title="No team members" description="Add a person to collaborate on case files." />}</div><div className="info-panel"><UsersRound size={20} /><div><strong>Case access is explicit</strong><p>New accounts do not automatically gain access to case documents. Add them to a case as a viewer or editor. Administrators and auditors have organization level visibility.</p></div></div>{open && <Modal title="Add a person" eyebrow="ORGANIZATION ACCOUNT" onClose={() => setOpen(false)}><form className="form-stack" onSubmit={submit}><label>Full name<input value={name} onChange={event => setName(event.target.value)} minLength={2} maxLength={160} required placeholder="Full name" /></label><label>Work email<input value={email} onChange={event => setEmail(event.target.value)} type="email" required placeholder="person@department.gov.in" /></label><label>Temporary password<input value={password} onChange={event => setPassword(event.target.value)} type="password" minLength={12} required placeholder="At least 12 characters" /><span className="field-help">Share this directly with the person through your organization’s approved channel.</span></label><label>Organization role<select value={role} onChange={event => setRole(event.target.value)}><option value="investigator">Investigator</option><option value="legal">Legal</option><option value="auditor">Auditor</option><option value="admin">Administrator</option></select></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Creating…" : "Create account"}</button></div></form></Modal>}</>;
}
