import { useEffect, useState, type FormEvent } from "react";
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Activity, ArrowRight, BriefcaseBusiness, ChevronDown, FileText, FolderClosed, LayoutDashboard, LockKeyhole, LogOut, Menu, Moon, Search, Settings2, ShieldCheck, Sun, UsersRound, X } from "lucide-react";
import { get, getToken, post, setToken } from "./api";
import { WorkspaceContext, useWorkspace } from "./context";
import type { CaseFile, User } from "./types";
import { Modal, initials } from "./ui";
import DashboardPage from "./pages/Dashboard";
import CasesPage from "./pages/Cases";
import CaseDetailPage from "./pages/CaseDetail";
import DocumentsPage from "./pages/Documents";
import ActivityPage from "./pages/Activity";
import TeamPage from "./pages/Team";
import SettingsPage from "./pages/Settings";

const NAV = [
  { to: "/", label: "Overview", icon: LayoutDashboard },
  { to: "/cases", label: "Case files", icon: FolderClosed },
  { to: "/documents", label: "Documents", icon: FileText },
  { to: "/activity", label: "Audit trail", icon: Activity },
  { to: "/team", label: "People & access", icon: UsersRound },
  { to: "/settings", label: "Settings", icon: Settings2 },
];

function Brand() { return <div className="brand"><span className="brand-mark"><ShieldCheck size={23} strokeWidth={2} /></span><span className="brand-copy"><strong>CaseVault</strong><small>SECURE RECORDS</small></span></div>; }

function AuthScreen({ initialized, onSuccess, theme, toggleTheme }: { initialized: boolean; onSuccess: (user: User, token: string) => void; theme: "light" | "dark"; toggleTheme: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [setupCode, setSetupCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError("");
    try { const result = await post<{ token: string; user: User }>(initialized ? "/auth/login" : "/auth/setup", initialized ? { email, password } : { name, email, password }, initialized ? undefined : { "X-Setup-Token": setupCode }); onSuccess(result.user, result.token); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to sign in."); }
    finally { setBusy(false); }
  }
  return <div className="auth-shell"><div className="auth-aside"><Brand /><div className="auth-illustration"><div className="auth-illustration-icon"><BriefcaseBusiness size={35} /></div><span>TRUSTED WORKSPACE</span><h1>Every case. Every document. Accounted for.</h1><p>Organize sensitive legal and investigation records with clear access, immutable versions, and a verifiable chain of activity.</p><div className="auth-features"><div><LockKeyhole size={18} /> Encrypted evidence storage</div><div><Activity size={18} /> Traceable actions</div><div><FolderClosed size={18} /> Case by case access</div></div></div><small>Built for responsible investigative work · SIH 26190</small></div>
    <div className="auth-main"><button className="icon-button auth-theme" onClick={toggleTheme} aria-label="Toggle theme">{theme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button><div className="auth-card"><div className="eyebrow">{initialized ? "WELCOME BACK" : "FIRST RUN SETUP"}</div><h2>{initialized ? "Sign in to CaseVault" : "Create your workspace"}</h2><p>{initialized ? "Enter your account details to continue securely." : "Create the first administrator account for this installation."}</p><form onSubmit={submit} className="form-stack">{!initialized && <label>Full name<input value={name} onChange={event => setName(event.target.value)} minLength={2} maxLength={160} required placeholder="Your full name" /></label>}<label>Work email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required placeholder="you@department.gov.in" /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={initialized ? 1 : 12} required placeholder={initialized ? "Enter your password" : "At least 12 characters"} /></label>{!initialized && <label>Setup token<input value={setupCode} onChange={event => setSetupCode(event.target.value)} required placeholder="From data folder or environment" /><span className="field-help">Find it in backend/data/casevault.setup-token as hex, or set DMS_SETUP_TOKEN.</span></label>}{error && <div className="form-error">{error}</div>}<button className="button button-primary button-full" disabled={busy}>{busy ? "Please wait…" : initialized ? "Sign in" : "Create workspace"}<ArrowRight size={17} /></button></form><div className="auth-foot"><ShieldCheck size={15} /> Protected by session based access</div></div></div></div>;
}

function NewCaseModal({ onClose }: { onClose: () => void }) {
  const { notify, refresh } = useWorkspace(); const navigate = useNavigate();
  const [reference, setReference] = useState(""); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState("investigation"); const [classification, setClassification] = useState("confidential"); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { const result = await post<CaseFile>("/cases", { reference, title, description, category, classification }); refresh(); notify("Case file created."); onClose(); navigate(`/cases/${result.id}`); } catch (cause) { notify(cause instanceof Error ? cause.message : "Could not create case.", true); } finally { setBusy(false); } }
  return <Modal title="Create case file" eyebrow="NEW CASE" onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="form-grid"><label>Case reference<input value={reference} onChange={event => setReference(event.target.value)} required minLength={3} maxLength={60} placeholder="FIR/2026/0042" /></label><label>Category<select value={category} onChange={event => setCategory(event.target.value)}><option value="investigation">Investigation</option><option value="litigation">Litigation</option><option value="evidence">Evidence</option><option value="legal_notice">Legal notice</option><option value="other">Other</option></select></label></div><label>Case title<input value={title} onChange={event => setTitle(event.target.value)} required minLength={3} maxLength={240} placeholder="A clear, descriptive title" /></label><label>Description<textarea value={description} onChange={event => setDescription(event.target.value)} rows={3} maxLength={5000} placeholder="Brief context for authorized team members" /></label><label>Classification<select value={classification} onChange={event => setClassification(event.target.value)}><option value="internal">Internal</option><option value="confidential">Confidential</option><option value="restricted">Restricted</option></select></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Creating…" : "Create case"}<ArrowRight size={16} /></button></div></form></Modal>;
}

function Shell({ user, onLogout, theme, toggleTheme }: { user: User; onLogout: () => void; theme: "light" | "dark"; toggleTheme: () => void }) {
  const location = useLocation(); const navigate = useNavigate();
  const [refreshKey, setRefreshKey] = useState(0); const [newCase, setNewCase] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [toast, setToast] = useState<{ message: string; error: boolean } | null>(null); const [search, setSearch] = useState("");
  const section = NAV.find(item => item.to !== "/" && location.pathname.startsWith(item.to))?.label ?? "Overview";
  useEffect(() => { setMobileOpen(false); }, [location.pathname]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 4400); return () => clearTimeout(timer); }, [toast]);
  const notify = (message: string, error = false) => setToast({ message, error });
  function logout() { post("/auth/logout").catch(() => undefined).finally(() => { setToken(null); onLogout(); }); }
  return <WorkspaceContext.Provider value={{ user, refreshKey, refresh: () => setRefreshKey(value => value + 1), notify, openNewCase: () => setNewCase(true), theme, toggleTheme }}><div className="app-shell"><aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><div className="sidebar-top"><Brand /><button className="icon-button mobile-close" onClick={() => setMobileOpen(false)} aria-label="Close menu"><X size={18} /></button></div><div className="workspace-switch"><div className="workspace-avatar"><BriefcaseBusiness size={18} /></div><div><strong>Investigations</strong><span>Secure workspace</span></div><ChevronDown size={15} /></div><div className="sidebar-label">WORKSPACE</div><nav className="nav-list">{NAV.map(item => <NavLink key={item.to} end={item.to === "/"} to={item.to} className={({ isActive }) => `nav-item ${isActive ? "nav-active" : ""}`}><item.icon size={18} strokeWidth={1.8} /><span>{item.label}</span></NavLink>)}</nav><div className="sidebar-bottom"><div className="secure-note"><ShieldCheck size={18} /><div><strong>Protected workspace</strong><span>Access is recorded and reviewed</span></div></div><button className="profile" onClick={logout} title="Sign out"><span className="avatar">{initials(user.name)}</span><span className="profile-copy"><strong>{user.name}</strong><small>{user.role}</small></span><LogOut size={17} /></button></div></aside>{mobileOpen && <div className="mobile-scrim" onClick={() => setMobileOpen(false)} />}
    <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="icon-button mobile-menu" onClick={() => setMobileOpen(true)} aria-label="Open menu"><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><span className="breadcrumb-slash">/</span><strong>{section}</strong></div></div><div className="topbar-right"><form className="global-search" onSubmit={event => { event.preventDefault(); navigate(`/documents?q=${encodeURIComponent(search)}`); }}><Search size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search documents" aria-label="Search documents" /><kbd>↵</kbd></form><button className="icon-button" onClick={toggleTheme} title={`Switch to ${theme === "light" ? "dark" : "light"} theme`} aria-label="Toggle theme">{theme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button><span className="topbar-divider" /><span className="avatar avatar-small">{initials(user.name)}</span></div></header><main className="content"><Routes><Route path="/" element={<DashboardPage />} /><Route path="/cases" element={<CasesPage />} /><Route path="/cases/:caseId" element={<CaseDetailPage />} /><Route path="/documents" element={<DocumentsPage />} /><Route path="/activity" element={<ActivityPage />} /><Route path="/team" element={<TeamPage />} /><Route path="/settings" element={<SettingsPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div></div>{newCase && <NewCaseModal onClose={() => setNewCase(false)} />}{toast && <div className={`toast ${toast.error ? "toast-error" : ""}`} role="status"><span>{toast.message}</span><button onClick={() => setToast(null)} aria-label="Dismiss"><X size={16} /></button></div>}</WorkspaceContext.Provider>;
}

export default function CaseVaultApp() {
  const [theme, setTheme] = useState<"light" | "dark">(() => localStorage.getItem("casevault_theme") === "dark" ? "dark" : "light"); const [user, setUser] = useState<User | null>(null); const [initialized, setInitialized] = useState(true); const [booting, setBooting] = useState(true); const [bootError, setBootError] = useState("");
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("casevault_theme", theme); }, [theme]);
  useEffect(() => { const handler = () => setUser(null); window.addEventListener("casevault:unauthorized", handler); return () => window.removeEventListener("casevault:unauthorized", handler); }, []);
  useEffect(() => { let active = true; async function boot() { try { const state = await get<{ initialized: boolean }>("/auth/state"); if (!active) return; setInitialized(state.initialized); if (getToken()) { try { const me = await get<User>("/auth/me"); if (active) setUser(me); } catch { setToken(null); } } setBootError(""); } catch (cause) { if (active) setBootError(cause instanceof Error ? cause.message : "Unable to connect."); } finally { if (active) setBooting(false); } } void boot(); return () => { active = false; }; }, []);
  if (booting) return <div className="boot-screen"><Brand /><span className="spinner" /></div>;
  if (bootError) return <div className="boot-screen"><Brand /><h2>Workspace unavailable</h2><p>{bootError}</p><button className="button button-primary" onClick={() => window.location.reload()}>Try again</button></div>;
  if (!user) return <AuthScreen initialized={initialized} theme={theme} toggleTheme={() => setTheme(value => value === "light" ? "dark" : "light")} onSuccess={(nextUser, token) => { setToken(token); setUser(nextUser); setInitialized(true); }} />;
  return <Shell user={user} onLogout={() => setUser(null)} theme={theme} toggleTheme={() => setTheme(value => value === "light" ? "dark" : "light")} />;
}
