import { useEffect, useState, type ChangeEvent } from "react";
import { ArrowDownToLine, CheckCircle2, Eye, FileText, Fingerprint, Plus, ShieldCheck } from "lucide-react";
import { evidenceBlob, get, upload } from "./api";
import { useWorkspace } from "./context";
import type { Document, Version } from "./types";
import { Badge, fmtDate, fmtSize, Modal, label } from "./ui";

export default function DocumentPanel({ document, onClose, canEdit = false, onUpdated }: { document: Document; onClose: () => void; canEdit?: boolean; onUpdated?: (document: Document) => void }) {
  const { notify } = useWorkspace();
  const [preview, setPreview] = useState<{ url: string; mime: string; text?: string } | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [verified, setVerified] = useState<Record<string, boolean>>({});
  useEffect(() => () => { if (preview?.url) URL.revokeObjectURL(preview.url); }, [preview]);
  const path = (version: Version) => `/documents/${document.id}/versions/${version.id}`;
  async function download(version: Version) { setBusyId(version.id); try { const blob = await evidenceBlob(`${path(version)}/download`); const url = URL.createObjectURL(blob); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = version.filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 30000); notify("Evidence download recorded in the audit trail."); } catch (error) { notify(error instanceof Error ? error.message : "Download failed.", true); } finally { setBusyId(null); } }
  async function showPreview(version: Version) { setBusyId(version.id); try { const blob = await evidenceBlob(`${path(version)}/download`); if (preview?.url) URL.revokeObjectURL(preview.url); if (version.mime_type === "text/plain") setPreview({ url: "", mime: version.mime_type, text: await blob.text() }); else setPreview({ url: URL.createObjectURL(blob), mime: version.mime_type }); } catch (error) { notify(error instanceof Error ? error.message : "Preview failed.", true); } finally { setBusyId(null); } }
  async function verify(version: Version) { setBusyId(version.id); try { await get(`${path(version)}/verify`); setVerified(value => ({ ...value, [version.id]: true })); notify(`Version ${version.number} passed encryption and SHA-256 verification.`); } catch (error) { notify(error instanceof Error ? error.message : "Integrity check failed.", true); } finally { setBusyId(null); } }
  async function addVersion(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusyId("upload"); try { const form = new FormData(); form.set("file", file); const updated = await upload<Document>(`/documents/${document.id}/versions`, form); onUpdated?.(updated); notify("New version uploaded. The previous version remains available."); } catch (error) { notify(error instanceof Error ? error.message : "Upload failed.", true); } finally { setBusyId(null); event.target.value = ""; } }
  return <Modal wide title={document.title} eyebrow={`${label(document.kind)} · ${document.case_reference}`} onClose={onClose}><div className="doc-meta"><span><FileText size={16} /> {document.versions.length} version{document.versions.length === 1 ? "" : "s"}</span><Badge value={document.classification} /><span>Added {fmtDate(document.created_at)}</span></div><div className="document-notice"><ShieldCheck size={19} /><div><strong>Original versions are preserved</strong><span>Each upload is encrypted and receives its own SHA-256 fingerprint. New versions never replace earlier files.</span></div></div><div className="section-title-row"><div className="section-title">Version history</div>{canEdit && <label className="button button-secondary button-small file-button"><Plus size={15} /> {busyId === "upload" ? "Uploading…" : "Add version"}<input type="file" accept=".pdf,.docx,.txt,.png,.jpg,.jpeg" onChange={addVersion} disabled={busyId === "upload"} /></label>}</div><div className="version-list">{document.versions.map(version => <div className="version-row" key={version.id}><div className="version-number">v{version.number}</div><div className="version-info"><strong>{version.filename}</strong><span>{fmtSize(version.byte_size)} · {fmtDate(version.created_at)} · Text: {label(version.extraction_status)}</span><code><Fingerprint size={13} /> {version.sha256.slice(0, 24)}…</code></div><div className="version-actions"><button className="icon-button" title="Verify integrity" aria-label={`Verify version ${version.number}`} onClick={() => verify(version)} disabled={busyId === version.id}>{verified[version.id] ? <CheckCircle2 size={18} className="success-text" /> : <ShieldCheck size={18} />}</button>{["application/pdf", "image/png", "image/jpeg", "text/plain"].includes(version.mime_type) && <button className="icon-button" title="Preview" aria-label={`Preview version ${version.number}`} onClick={() => showPreview(version)} disabled={busyId === version.id}><Eye size={18} /></button>}<button className="icon-button" title="Download" aria-label={`Download version ${version.number}`} onClick={() => download(version)} disabled={busyId === version.id}><ArrowDownToLine size={18} /></button></div></div>)}</div>{preview && <div className="preview-panel"><div className="section-title">Evidence preview</div>{preview.text !== undefined ? <pre>{preview.text}</pre> : preview.mime === "application/pdf" ? <iframe src={preview.url} title="Document preview" /> : <img src={preview.url} alt="Evidence preview" />}</div>}</Modal>;
}
